const $=s=>document.querySelector(s), state={items:[],index:0,mode:'pending',scale:1,x:0,y:0,drag:null,reasons:[]};
const api=async(path,options={})=>{const r=await fetch('/api/'+path,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok)throw Error(j.error||'请求失败');return j};
const dbp=new Promise((ok,bad)=>{const q=indexedDB.open('image-review',1);q.onupgradeneeded=()=>q.result.createObjectStore('ops',{keyPath:'op_id'});q.onsuccess=()=>ok(q.result);q.onerror=()=>bad(q.error)});
async function idbPut(op){const db=await dbp;await new Promise((ok,bad)=>{const t=db.transaction('ops','readwrite');t.objectStore('ops').put(op);t.oncomplete=ok;t.onerror=()=>bad(t.error)})}
async function idbDelete(id){const db=await dbp;db.transaction('ops','readwrite').objectStore('ops').delete(id)}
async function flush(){const db=await dbp,ops=await new Promise((ok,bad)=>{const q=db.transaction('ops').objectStore('ops').getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>bad(q.error)});for(const op of ops){try{await api('action',{method:'POST',body:JSON.stringify(op)});await idbDelete(op.op_id)}catch{break}}}
function imageUrl(path){return '/image/'+path.split('/').map(encodeURIComponent).join('/')}
function transform(){for(const img of [$('#original'),$('#modified')])img.style.transform=`translate(calc(-50% + ${state.x}px),calc(-50% + ${state.y}px)) scale(${state.scale*(+img.dataset.fit||1)})`}
function fit(){state.scale=1;state.x=state.y=0;transform()}
function render(){const item=state.items[state.index],empty=!item;$('#empty').classList.toggle('hidden',!empty);for(const x of ['#original','#modified'])$(x).removeAttribute('src');if(item){$('#original').src=imageUrl(item.original_path);$('#modified').src=imageUrl(item.current_path);$('#id').textContent=`${item.folder}/${item.image_id} · v${String(item.current_version).padStart(3,'0')}`;fit()}else $('#id').textContent='';$('#counter').textContent=`${state.items.length?state.index+1:0} / ${state.items.length}`;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=empty||state.mode!=='pending')}
async function load(){try{const p=await api('project');$('#project').textContent=p.project||'未选择项目';if(!p.project){$('#projectDialog').showModal();return}await flush();state.reasons=(await api('settings')).redo_reasons;state.items=(await api(state.mode==='redo'?'redo':'items')).items;state.index=Math.min(state.index,Math.max(0,state.items.length-1));render()}catch(e){message(e.message)}}
function message(s){$('#message').textContent=s;setTimeout(()=>{$('#message').textContent=''},3500)}
async function act(action,reason=null){const item=state.items[state.index];if(!item)return;const op={op_id:crypto.randomUUID(),image_id:item.image_id,action,reason};await idbPut(op);state.items.splice(state.index,1);state.index=Math.min(state.index,Math.max(0,state.items.length-1));render();try{await api('action',{method:'POST',body:JSON.stringify(op)});await idbDelete(op.op_id)}catch(e){message('已本地保存，等待后台同步：'+e.message)}}
function askReason(){const box=$('#reasons');box.innerHTML='';state.reasons.forEach((r,i)=>{const b=document.createElement('button');b.className='reason';b.type='button';b.textContent=`${i+1}. ${r}`;b.onclick=()=>{$('#reasonDialog').close();act('redo',r)};box.appendChild(b)});$('#reasonDialog').showModal()}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>b.dataset.action==='redo'?askReason():act(b.dataset.action));
$('#skipReason').onclick=()=>act('redo');$('#undo').onclick=async()=>{const r=await api('undo',{method:'POST',body:'{}'});message(r.message||'已撤销');await load()};
$('#export').onclick=async()=>{try{const r=await api('export',{method:'POST',body:'{}'});message(`已导出 ${r.exported} 张`);await load()}catch(e){message('导出失败，可重试：'+e.message)}};
$('#editReasons').onclick=async()=>{const value=prompt('每行一个待重做原因：',state.reasons.join('\n'));if(value===null)return;const redo_reasons=value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!redo_reasons.length){message('至少保留一个原因');return}try{await api('settings',{method:'POST',body:JSON.stringify({redo_reasons})});state.reasons=redo_reasons;message('原因已保存')}catch(e){message(e.message)}};
$('#choose').onclick=()=>$('#projectDialog').showModal();$('#projectSave').onclick=async e=>{e.preventDefault();try{await api('project',{method:'POST',body:JSON.stringify({path:$('#projectPath').value})});$('#projectDialog').close();await load()}catch(x){message(x.message)}};
function tab(mode){state.mode=mode;state.index=0;$('#reviewTab').classList.toggle('active',mode==='pending');$('#redoTab').classList.toggle('active',mode==='redo');load()}$('#reviewTab').onclick=()=>tab('pending');$('#redoTab').onclick=()=>tab('redo');
addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')){if($('#reasonDialog').open&&/^[1-9]$/.test(e.key)){const b=$$('.reason')[+e.key-1];if(b)b.click()}return}const k=e.key.toLowerCase();if(k==='a')act('accept');else if(k==='r')askReason();else if(k==='x')act('reject');else if(k==='z'||((e.ctrlKey||e.metaKey)&&k==='z')){$('#undo').click();e.preventDefault()}else if(e.key==='ArrowLeft'){state.index=Math.max(0,state.index-1);render()}else if(e.key==='ArrowRight'){state.index=Math.min(state.items.length-1,state.index+1);render()}});
function $$(s){return [...document.querySelectorAll(s)]}$$('.pane').forEach(p=>{p.onwheel=e=>{e.preventDefault();state.scale=Math.min(10,Math.max(.1,state.scale*Math.exp(-e.deltaY*.001)));transform()};p.onpointerdown=e=>{p.setPointerCapture(e.pointerId);state.drag={x:e.clientX-state.x,y:e.clientY-state.y}};p.onpointermove=e=>{if(state.drag){state.x=e.clientX-state.drag.x;state.y=e.clientY-state.drag.y;transform()}};p.onpointerup=()=>state.drag=null;p.ondblclick=fit});
for(const img of [$('#original'),$('#modified')]){img.onload=()=>{const pane=img.parentElement;img.dataset.fit=Math.min((pane.clientWidth-20)/img.naturalWidth,(pane.clientHeight-20)/img.naturalHeight,1);transform()};img.onerror=()=>message('图片文件缺失、损坏或无法解码')}
async function poll(){try{const next=(await api(state.mode==='redo'?'redo':'items')).items;const signature=x=>x.map(i=>i.image_id+':'+i.current_version).join('|');if(signature(next)!==signature(state.items)){const current=state.items[state.index]?.image_id;state.items=next;state.index=Math.max(0,next.findIndex(x=>x.image_id===current));render()}}catch(e){message(e.message)}}
load();setInterval(poll,3000);
